### PR TITLE
basic repl support

### PR DESCRIPTION
**Pull request by galchinsky**
Just #395 with one commit

### CODE REVIEW

**Comment by jckarter** [comment]
Just FYI, you can update a pull request by pushing additional commits to the pull request's branch.

**Comment by galchinsky** [comment]
I had to revert commits from my 'orig' branch, because I couldn't make rebase work. It probally closed that pull request automatically

**Comment by jckarter** [comment]
Is something like this supposed to work yet? After I define a function in the repl, trying to call it hangs.

```
% ./build/compiler/src/clay -Ilib-clay examples/hello.clay -repl
Clay interpreter
:q to exit
:print {identifier} to print an identifier
clay>main();
ExprStatement(Call(NameRef(Identifier(main)), ExprList([]), ExprList([])))
Hello World
clay>^wut() { println("wut"); }
0: Procedure(Identifier(wut))
1: Overload(NameRef(Identifier(wut)), Code([], NULL, [], 0, [], NULL, Block([
  ExprStatement(Call(NameRef(Identifier(println)), ExprList([StringLiteral(Identifier(wut))]), ExprList([])))])), 0, 0)
clay>wut();
ExprStatement(Call(NameRef(Identifier(wut)), ExprList([]), ExprList([])))
```

**Comment by jckarter** [comment]
You also asked about the LLVM equivalent to `istream`. There isn't one for interactive use, but you could use `fgets()` instead. The standard C++ `iostream` is bloated, slow, and adds to startup time, so it's preferable to use LLVM `raw_ostream` and C stdio instead.

**Comment by galchinsky** [comment]
No, toplevels shouldn't work. Trying to call a function made an 0x000005 exception in visual studio 2010. Now in my gcc it is just silent.
I think something is missing in https://github.com/galchinsky/clay/blob/orig/compiler/src/interactive.cpp#L79 , but I don't know what.

**Comment by jckarter** [comment]
As I mentioned by email before, toplevels need to initialized and added to the proper lookup tables as if by `initModule`. Your current code, which appends them to a module then reinitializes the module, isn't going to work because `initModule` isn't designed to be called multiple times on the same data like that. It may work better to create a new module and load and initialize that. You could maintain the illusion of a common namespace by chaining the repl modules with public imports, something like this:

```
// first interactive module
public import __main__.*;

<first toplevel>
```

```
// second interactive module
public import __interactive_0__.*;

<second toplevel>
```

```
public import __interactive_1__.*;

<third toplevel>
```

and so on.

**Comment by jckarter** [comment]
I looked into the problem with it crashing after optimizing. It makes perfect sense—after optimization, the IR is updated in-place and inlined functions are eliminated, so when code generated by the repl tries to call an inlined function it ends up trying to call an IR function that no longer exists. Disabling optimization for the repl is the right thing to do.

**Comment by galchinsky** [comment]
Isn't it possible to extract some code from initModule to init only new toplevels?

**Comment by jckarter** [comment]
@galchinsky Possibly. I worry that this code wasn't designed to be called in a context outside of immediately after parsing. The main things I can think of that need to happen are:
- add newly defined symbols to the module's env
- add overloads to the proper symbols' overload lists, and invalidate any cached invoke entry info
- run constructors and install destructors for new global variables

**Comment by galchinsky** [comment]
Where does the 2nd and 3rd happen in code now?

**Comment by jckarter** [comment]
Overload setup is performed by `initOverload`. Global variables are normally instantiated by codegen on demand; see `codegenGVarInstance` in codegen.cpp. `codegenGVarInstance` won't work as-is because the IRBuilder contexts for the normal global ctor and dtor functions has already been closed. You'll need to create new functions and contexts; see `codegenEntryPoints`, `initializeCtorsDtors`, and `generateCtorsDtors`.

Another case to consider is variant `instance` forms. I don't think the toplevel can support these because an `instance` can change the runtime representation of a variant type, which would screw up any currently extant variant objects.

**Comment by galchinsky** [comment]
Toplevel functions are work now if they are not overloaded.

```
clay>^foo(x, y){println(x + y);}
clay>foo(1, 2);
3
clay>^main(x, y){println(x + y);}
0: Procedure(Identifier(main))
###############################
main(x, y){println(x + y);}
^
###############################
(1,0): error: name redefined: main

```

It's quite obvious why it is redefined, so I'll fix it and add ctors-dtors for global vars the next time, not today

**Comment by galchinsky** [comment]
Oh, it shouldn't, I forgot the syntax. Everything is OK with ^overload main... So global vars are the next

**Comment by jckarter** [comment]
Would it also be possible to support starting the repl without an initial module? You could start with an empty module importing the prelude and then support top-level import forms to access additional modules.

**Comment by galchinsky** [comment]
I got stuck with imports. If it would work, repl could start without an initial module.
https://github.com/galchinsky/clay/blob/orig/compiler/src/interactive.cpp#L76
I parse an import to vector<ImportPtr>, do loadDependent ( it is just an extract from [loadDependents](https://github.com/galchinsky/clay/blob/orig/compiler/src/loader.cpp#L294)), then do initModule, it seems that i forgot to call something that installs overloads.
I don't think that this code is ready for pulling, so I'm pushing it to my repo just to know if I forgot something in loadImports(). I'll continue next weekend.

**Comment by galchinsky** [comment]
```
$cat emptyprinter.clay 
import printer.(println);
main(){}
$cat one.clay
add(x, y) = x + y;
```

This works:

```
$ ./clay -repl emptyprinter.clay
clay>import one.(add);
clay>println(add(1,2));
3
```

This doesn't:

```
$./clay -repl
clay>import printer.(println);
clay>println(5);
ExprStatement(Call(NameRef(Identifier(println)), ExprList([IntLiteral(5)]), ExprList([])))
###############################

[T when VariantMember?(OSError, T)]
overload Exception(forward x:T) = Exception(OSError(x));
-------------------------------------------^

printErrorMessageTo(stream, code:Int) {
###############################
/home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/os/errors/errors.clay(28,43): error: no matching overload found
    /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/io/errors/errors.clay(27,0)
        predicate "VariantMember?(IOError, T)" failed
    /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/os/errors/errors.clay(27,0)
        predicate "VariantMember?(OSError, T)" failed
    /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/core/exceptions/exceptions.clay(21,0)
        incorrect number of arguments: expected 0 arguments, got 1 arguments
    76 universal overloads not shown (show with -full-match-errors option)

compilation context: 
    Exception(OSError)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/os/errors/errors.clay(28,43):
    Exception(IOError)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/io/errors/errors.clay(28,43):
    Exception(GenericIOError)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/core/exceptions/exceptions.clay(60,42):
    allocateExceptionData(GenericIOError, StringLiteralRef, UInt32)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/core/exceptions/exceptions.clay(65,35):
    throwValue(GenericIOError)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/io/files/raw/platform/platform.unix.clay(98,8):
    writeBytes(RawFile, Pointer[UInt8], UInt64)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/io/streams/streams.clay(20,25):
    updateAssign(Static[+], UInt64, UInt64)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/io/streams/streams.clay(20,8):
    write(RawFile, Pointer[UInt8], UInt64)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/printer/types/types.clay(141,9):
    printWithSprintf(RawFile, Static["%d"], Int32)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/printer/types/types.clay(45,20):
    printTo(RawFile, Int32)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/printer/types/types.clay(25,15):
    printTo(RawFile, Int32, Char)
  /home/dmitry/clay/qtcreator-build/compiler/src/../../../lib-clay/printer/printer.clay(26,11):
    println(Int32)
  (1,7):
    external __replAnonymousFunction__0
```

The same with import math.(sin);

**Comment by galchinsky** [comment]
This also doesnt

```
$cat one.clay
var z = 5;
add(x, y) = z + x + y;
$./clay -repl
clay>import one.(add);  
clay>add(1,2);
ExprStatement(Call(NameRef(Identifier(add)), ExprList([IntLiteral(1), IntLiteral(2)]), ExprList([])))
signal 11!

compilation context: 
    infixOperator(Int32, Static[+], Int32, Static[+], Int32)
  ./one.clay(2,14):
    add(Int32, Int32)
  (1,3):
    external __replAnonymousFunction__0
Ошибка сегментирования
```

Global vars are not initialized via loadDependents+initModule?

**Comment by jckarter** [comment]
Global variables are normally instantiated on demand by codegen. `codegenEntryPoints` sets up special codegen contexts for the global ctor and dtor:

https://github.com/jckarter/clay/blob/master/compiler/src/codegen.cpp#L6912

You will need to construct contexts, set up the constructorCtx and destructorCtx pointers, and call initializeCtorsDtors before codegenning REPL input in order to handle newly instantiated global variables. After codegen, you can then call finalizeCtorsDtors, invoke the new constructor function immediately to initialize globals, and add the new destructor function to global_dtors so it will be run at exit.

**Comment by jckarter** [comment]
The problem with Exception probably arises because variant `instance`s aren't taking effect. As I said before, this is problematic because an instance can change the size and layout of a variant type, which would corrupt any code that expects the old layout of the type. I'm not sure this can be supported without changing how variants work when in repl mode.

**Comment by jckarter** [comment]
I see you got globals working—nice work! As a temporary workaround for the lack of repl support for variant instances, one thing you could do is perhaps have a `prelude.repl` module that is used as the main module if the repl is launched without an explicit main module. This module could load the io, printer, and other common libraries so that their exception instances are ready before the repl is started.

**Comment by stepancheg** [comment]
BTW, if you are planning to commit these patches any time soon, I'd also really like to have REPL tests included. Something similar to [what is done in Kotlin](https://github.com/JetBrains/kotlin/commit/bace845b493dd1005ff4a8dea600a10799e72d12#L2R1).

**Comment by galchinsky** [comment]
Is there a way to re-codegen a module? Simple codegenEntryPoints(module, false) doesn't work

**Comment by jckarter** [comment]
`codegenEntryPoints` only codegens the `main` and `external` entry points. What are you trying to do?

**Comment by galchinsky** [comment]
I'm trying to add :rebuild command for interpreter that rebuilds everything, so variant instances should load.
Something like
1. Dump globals
2. Rebuld all, [run new globals constuctors etc]
3. Return globals

**Comment by jckarter** [comment]
I think the only way to practically do that would be to start from scratch and reload everything, replaying your REPL imports and inputs as if they were a module source file.

**Comment by jckarter** [comment]
Superseded by #416

**Pull request closed without merging**
