### PR TITLE
Fix #272 by changing dotted import behavior

### LINKED ISSUE #272: Module equality breaks qualified module names

### PR DESCRIPTION
**Pull request by jckarter**
- Eliminate ModuleHolders and use Module objects to represent module values directly
- Change the behavior of field ref expressions as follows:
  - If the field reference form textually matches a qualified module name imported in the current module, evaluate to that module. For example:
    
    ```
      import foo.bar;
      foo_bar() = foo.bar;
    ```
  - Otherwise, evaluate the left-hand expression and proceed as before:
    - If the left-hand expression evaluates to a module value, look up the right-hand identifier in the module and evaluate to the found object
    - Otherwise, evalue the expression as `__operators__.fieldRef(left, "right")`
  - Explicitly disallow `public import foo.bar;` without an alias. This didn't really work anyway, and doesn't make sense with the new implementation.

Dotted module names must be handled textually, because a module "foo.bar" is not an actual member of the module "foo". In order to properly support modules as first-class values, the former "module holder" implementation cannot work, because it is impossible to have equivalent static objects with different sets of members: Either different module holders representing the same module would be unequal, or submodules would have to be considered members of the parent module, which violates the current modularity and location independence of modules. This seems like the best way to me to support qualified module names and module values together. There is the weird behavior that a qualified name still works even if the root component is shadowed by a local name, but other than that, I think this usually does what you mean.

Fixes #272.

### CODE REVIEW

**Comment by ghost** [comment]
```
[lang/modules/imports/publicqualified]
Failure: unexpected compiler error
Expected:
 public imports of dotted module paths must have an "as <name>" alias
Actual:

 /usr/lib/gcc/x86_64-unknown-linux-gnu/4.7.2/../../../crt1.o(.text+0x20): error: undefined reference to 'main'
 clang: error: linker command failed with exit code 1 (use -v to see invocation)

[lang/modules/imports/dotted3]
Failure: compiler error
Error:

 ###############################
 main() {
     var foo = 1;
     foo.bar.a();
 -------^
 }

 ###############################
 /home/jeremy/dev/clay/clay/test/lang/modules/imports/dotted3/main.clay(5,7): error: no matching overload found
     /home/jeremy/dev/clay/clay/build/compiler/../../lib-clay/core/statics/statics.clay(60,0)
         pattern "#Module" did not match type "Int32" of argument 1
     /home/jeremy/dev/clay/clay/build/compiler/../../lib-clay/core/records/records.clay(4,0)
         predicate "RecordWithField?(T, FIELD)" failed
     76 universal overloads not shown (show with -full-match-errors option)

 compilation context: 
     fieldRef(Int32, Static["bar"])
   /home/jeremy/dev/clay/clay/test/lang/modules/imports/dotted3/main.clay(5,7):
     main()
   /home/jeremy/dev/clay/clay/build/compiler/../../lib-clay/core/system/system.clay(23,30):
     getExitCode()
   /home/jeremy/dev/clay/clay/build/compiler/../../lib-clay/core/system/system.clay(23,26):
     runMain(Int32, Pointer[Pointer[Int8]], Static[main])
   /home/jeremy/dev/clay/clay/build/compiler/../../lib-clay/core/system/system.clay(39,13):
     callMain(Static[main], Int32, Pointer[Pointer[Int8]])
     external main
```

**Comment by jckarter** [comment]
It looks like you're using an out of date compiler binary.

**Comment by ghost** [comment]
OK, i'll check that, ta.

**Comment by ghost** [comment]
Clean build (Debug) from master gives the same errors.

**Comment by jckarter** [comment]
`git status` ?

**Comment by ghost** [comment]
Clear status. To triple check i'm currently do a completely clean clone&test.

**Comment by jckarter** [comment]
What's the `[Compiler]` being used by runtests.py?

**Comment by jckarter** [comment]
Did you do the clean build in a different build directory? `runtests` looks in `build/compiler` by default.

**Comment by ghost** [comment]
The compiler used is the freshly built one at `build/compiler/clay`.

**Comment by ghost** [comment]
Interesting! The new clone only fails 3 of the new 'threads' tests (as it should as pthreads isn't linked yet).

**Comment by ghost** [comment]
Not to worry, just my own ineptitude (as usual), I was building from 'debug' dir instead of usual 'build' dir and of course the tests were using the 'build' dir.

**Comment by jckarter** [comment]
As I mentioned in #422, adding `buildflags.linux.txt` containing `-lpthread` should clear up the thread test failures.

**Comment by stepancheg** [comment]
@jckarter fixed in 510e2aee33dca4fe132af48c0690a8d69efcc544.

**Pull request closed without merging**
