### PR TITLE
Prohibit overloads of standalone functions

### LINKED ISSUE #406: Make normal procedures non-overloadable; require `define` for overloadable procedures
A function defined with a body, such as `foo(x) = x + 1;`, is currently equivalent to `define foo; overload foo(x) = x + 1;`. It would be clearer if functions that are intended to be overloaded were required to be created with `define` and then `overload`ed explicitly.

### PR DESCRIPTION
**Pull request by stepancheg**
This code is compilation error now.

```
foo() = 1;
overload foo(x) = 2;
```

Fixes #406 (except for `private overload` part).

### CODE REVIEW

**Comment by jckarter** [comment]
Looks good. Some function `define`s could benefit from more descriptive interface restrictions, but I understand that it's tedious to do all at once.

**Comment by galchinsky** [comment]
Does overload keyword really need now? It is quite verbose and seems useless

**Comment by jckarter** [comment]
Without the keyword, how do you distinguish defining a new function from overloading an existing function? You need to be able to overload symbols from other modules too.

**Comment by galchinsky** [comment]
Is this an internal compiler problem, or "user must know that he overloads, otherwise it can boom"?

**Comment by jckarter** [comment]
It's a language semantics issue. These do different things:

```
import foo.*;

bar() {} // define new bar
```

```
import foo.*;

overload bar() {} // add method to existing bar (imported from foo, or prelude)
```

**Comment by galchinsky** [comment]
So overload tells "please don't hide that symbol"?

**Comment by jckarter** [comment]
Yeah, making it explicit is a bit cleaner than using ad-hoc rules to distinguish hiding from overloading as in C++. That said, it should be possible to hide the `overload` keyword; one such way would be to do it as described in #410.

**Pull request merged**
