### PR TITLE
implement SHA-512

### PR DESCRIPTION
**Pull request by stepancheg**
- generify SHA-256 implementation
- implement SHA-512
- test SHA-256 works with unaligned data

### CODE REVIEW

**Comment by jckarter** [comment]
Maybe the module should be renamed to something like `crypto` or `hashing`, since the framework you've set up looks like it could admit non-SHA algorithms.

**Comment by stepancheg** [comment]
How about crypto.digest.sha2?

crypto module will have modules like

crypto.digest.md5
crypto.hmac

**Comment by jckarter** [comment]
That sounds reasonable.

**Comment by stepancheg** [comment]
Renamed to crypto.digest.sha2. Generic code need to be moved to crypto.digest. I'll do it when I implement MD5.

**Comment by jckarter** [comment]
Sounds good. Thanks!

**Pull request merged**
