### PR TITLE
Set clang include dir in clay-bindgen build - fix issue #419

### PR DESCRIPTION
**Pull request by ghost**
Clang lib tooling states the default dir should be used.
Have passed the dir into the clay-bindgen build via CMake.
This works on Archlinux, but could do with testing on other platforms.

### CODE REVIEW

**Comment by galchinsky** [comment]
works fine now

**Comment by jckarter** [comment]
I guess that works. It'd be nice to also figure out why libclang doesn't do this by default on Linux and fix it upstream too.

**Comment by ghost** [comment]
This issue has already been fixed upstream (clang 3.2 trunk).
Probably not worth merging this temporary fix if we are close to upgrading llvm/clang.

**Comment by jckarter** [comment]
Since LLVM 3.2 just forked a few days ago and will be released soon, it'd be a good time to port over to the new version. There are a couple other LLVM bug workarounds that could then be backed out too.

**Comment by jckarter** [comment]
Closing this until Clay is updated to use LLVM 3.2. If it's still a problem after that we can reopen.

**Pull request closed without merging**
