### PR TITLE
shorter no-arguments function syntax

### PR DESCRIPTION
**Pull request by stepancheg**
```
var f = -> foo();
```

is equivalent of

```
var f = () -> foo();
```

### CODE REVIEW

**Comment by jckarter** [comment]
Looks good. Are there any valid `expr expr` productions such that `…a -> b` would become ambiguously `…a) (-> b)` or `…(a -> b)`? I remember there being a reason this isn't already allowed.

Another nice shorthand would be to allow `{ block }` to be equivalent to `-> { block }` in expression context.

**Comment by stepancheg** [comment]
> Are there any valid expr expr productions ...?

I cannot remember any.

> Another nice shorthand would be to allow { block } to be equivalent to -> { block } in expression context.

To my opinion `{ 1 }` should be eqiuvalent of `1`, to avoid wats like this:

```
var n = if (true) { 1 } else { 2 };
```

I expect `n` to be integer.

And to allow tricks like:

```
var users = {
        var connection = openConnection();
        query(connection, "SELECT * FROM user")
   };
// connection is destroyed at this point
foo(users);
```

**Comment by jckarter** [comment]
I don't really like the current if expression syntax at all. I think parens would be better than braces for statement expressions, as in `var users = (var connection = openConnection(); query(connection, "…"));`

**Comment by stepancheg** [comment]
I like current if expression syntax. And I think that statements should look like expressions those results are ignored (partial "everything is expression" rule).

With your expression block syntax there will be two ways to declare a statement block:

```
{
    var x = 1;
    println(x);
};
(
    var x = 1;
    println(x)
);
```

**Comment by jckarter** [comment]
I agree that statement-expression equivalent is a good goal to strive for. At that point it makes sense to treat `;` as an operator like C's comma operator, that evaluates then discards its left-hand side. You're right that that makes braces redundant; they could either be made equivalent to parens or freed up to represent other syntax, such as lambdas.

**Comment by jckarter** [comment]
Another change to lambda syntax that might be nice would be to put the arrow first, as in `-> arg { ... }`. This would be slightly bulkier than the current `arg -> expr` special case, but it would eliminate the need for lookahead in the lambda syntax, and would also work naturally with the higher-order function syntax sugar:

```
maybe(?x) -> x {
    println(x);
} -> {
    println("nothing");
}
```

What do you all think?

**Comment by stepancheg** [comment]
I think it's too different from modern programming languages. I like current syntax (except for lambda last argument magic, that I'd probably drop without replacement).

**Comment by ghost** [comment]
Is there a some rationale for the use of trailing lambda arguments? Higher order function convention? Are the lambdas handled differently to other arguments?

I'm not a fan of either version of the lambda syntax, it all looks messy when wrapped up in various levels of parens. If i had to choose then i guess stick with the current syntax.

**Comment by jckarter** [comment]
The trailing lambda arguments are just to make higher-order functions (debatably) prettier; the arguments aren't handled differently at all. For custom control flow structures, it's a bit prettier to be able to put the block outside of the argument list and not have `});` all over the place, and with an additional kind of lambda that supported nonlocal `break`/`continue`/`return`, it would be nice to be able to turn `for` and `..for` into library functions.

**Comment by ghost** [comment]
I suppose lambdas are going to stay ugly unless major syntax changes are
introduced e.g. Structured code, fewer parens/braces. If the extra use of
colons aren't necessary i think trailing lambdas should be dropped for
consistency/simplicity. Maybe the colons could be useful elsewhere.

Interesting that you mention programmable control flow again, have you
checked out seed7? It looks pretty interesting. Not so sure an extensible
systems language would gain much traction, but i personally think that
clay's type propagation plus fully programmable would be a decent combo.

Sent from my BlackBerry® PlayBook™
www.blackberry.com

---

_From:_ "Joe Groff" notifications@github.com
_To:_ "jckarter/clay" clay@noreply.github.com
_CC:_ "agemogolk" agemogolk@gmail.com
_Sent:_ 10 October 2012 01:22
_Subject:_ Re: [clay] shorter no-arguments function syntax (#398)

The trailing lambda arguments are just to make higher-order functions
(debatably) prettier; the arguments aren't handled differently at all. For
custom control flow structures, it's a bit prettier to be able to put the
block outside of the argument list and not have }); all over the place, and
with an additional kind of lambda that supported nonlocal break/continue/
return, it would be nice to be able to turn for and ..for into library
functions.

—
Reply to this email directly or view it on
GitHubhttps://github.com/jckarter/clay/pull/398#issuecomment-9285055.

**Pull request merged**
