### PR TITLE
add more options for code generation

### PR DESCRIPTION
**Pull request by crabtw**
This patch adds command line options to allow us to specify more detailed features for target platform.

### CODE REVIEW

**Comment by stepancheg** [comment]
What are option names in clang to specify these features? I think we should be as compatible with clang command-line interface as possible.

**Comment by crabtw** [comment]
- -target-cpu
  Clang uses -mcpu.
- -target-features
  Clang expands them into several target dependent options.
  For example, x86 has -msse3, -mno-sse3 and ARM has -mfpu=vfpv3.
- -soft-float
  Clang uses -msoft-float.

-target-cpu and -soft-float can be renamed as clang's options.
For -target-features, some names are different from llvm accepted names.
We have to translate them before passing to `Target::createTargetMachine`.

**Comment by jckarter** [comment]
Yeah, Clang does some nontrivial translation of GCC-compatible -m switches to LLVM attributes. A good compromise might be to adopt `llc`'s `-mattr=...` syntax for target attributes so we're at least consistent with other LLVM tools, if not Clang and GCC.

**Comment by crabtw** [comment]
I renamed these options.

**Comment by jckarter** [comment]
Looks good.

**Comment by crabtw** [comment]
I revert -msoft-float to -soft-float so these options are compatible with llc now.

**Comment by ghost** [comment]
Merged in 3a006374b044c6df1c9dfd497ed65915964525bb. Thanks @crabtw.

**Pull request merged**
