### PR TITLE
Update math library imports

### PR DESCRIPTION
**Pull request by ghost**
Re-jigged the math lib imports to reduce dependencies of individual modules.
Remove -Dmath.Mode=libm flag. Now use import math.libm.\* or math.native.\* 
Default math lib can be set in the top-level math module.
Update libm tests to just test libm wrappers - not native functions.
No public imports below math.native module.
Merged overloads for each function into same module (complex/imag are native so no need for separate complex math function imports).
Fixed a few issues with complex/floats modules.
Removed static for from tests.

### CODE REVIEW

**Comment by jckarter** [comment]
Are all the public imports necessary? Having the same functions exposed through multiple library modules feels icky.

**Comment by jckarter** [comment]
I'm getting some test failures after pulling your latest patch:

```

[math/complex]
Failure: compiler error
Error:

 ###############################
 public import math.native.acosh.(acosh);
 public import math.native.asinh.(asinh);
 public import math.native.cot.(cot);
 --------------^
 public import math.native.acos.(acos);
 public import math.native.asin.(asin);
 ###############################
 /Users/joe/Documents/Code/others/clay/build/compiler/src/../../../lib-clay/math/native/complex.clay(16,14): error: module not found: math.native.cot

[math/native]
Failure: compiler error
Error:

 ###############################
 public import math.native.atan.*;
 public import math.native.atan2.*;
 public import math.native.cot.*;
 --------------^
 import math.native.constants.(M_PI);
 import numbers.floats.(floatFromBits,floatExponent,mantissaSize);
 ###############################
 /Users/joe/Documents/Code/others/clay/build/compiler/src/../../../lib-clay/math/native/native.clay(47,14): error: module not found: math.native.cot

[math/sqrt]
Failure: compiler error
Error:

 ###############################
 public import math.native.acosh.(acosh);
 public import math.native.asinh.(asinh);
 public import math.native.cot.(cot);
 --------------^
 public import math.native.acos.(acos);
 public import math.native.asin.(asin);
 ###############################
 /Users/joe/Documents/Code/others/clay/build/compiler/src/../../../lib-clay/math/native/complex.clay(16,14): error: module not found: math.native.cot

[operators/custom2]
Failure: compiler error
Error:

 ###############################
 public import math.native.atan.*;
 public import math.native.atan2.*;
 public import math.native.cot.*;
 --------------^
 import math.native.constants.(M_PI);
 import numbers.floats.(floatFromBits,floatExponent,mantissaSize);
 ###############################
 /Users/joe/Documents/Code/others/clay/build/compiler/src/../../../lib-clay/math/native/native.clay(47,14): error: module not found: math.native.cot
```

**Comment by ghost** [comment]
Hmm, yes, I'd assumed you would leave the pull request until I sorted 
out the import situation. I'm also updating the complex math modules as 
the current implementations were a temporary hack. I'll be done with all 
that in a day or so.

**Comment by ghost** [comment]
One thing I have done is take out the -Dmath.Mode=libm flag.  Setting a default can easily be done by changing the import in the top-level math module.

**Comment by jckarter** [comment]
That's a good change.

**Comment by ghost** [comment]
mathlib branch merged to master.

**Pull request closed without merging**
